const config = require('tailwindcss/defaultConfig');

module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Light Duolingo theme values mapped to old keys to unify style instantly
        "dark-bg": "#FAFAF9",
        "dark-surface": "#FFFFFF",
        "dark-surface-light": "#EEEEEE",
        "accent-green": "#58CC02",
        "accent-green-hover": "#2B6C00",
        "text-primary": "#1A1C1C",
        "text-secondary": "#5F6A59",
        "text-tertiary": "#A6A6A6",
        "error-red": "#BA1A1A",
        "success-green": "#58CC02",
        "warning-orange": "#FBB724",
        "info-blue": "#006590",

        // Additional Duolingo tokens for onboarding and preview screens
        "surface-variant": "#e3e2e2",
        "secondary-fixed": "#c8e6ff",
        "outline": "#6f7b64",
        "secondary-container": "#2fb8ff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f3131",
        "surface-container": "#eeeeed",
        "on-primary": "#ffffff",
        "surface-bright": "#faf9f9",
        "on-tertiary-container": "#574300",
        "on-primary-container": "#1e5000",
        "surface-container-highest": "#e3e2e2",
        "on-tertiary": "#ffffff",
        "on-surface": "#1a1c1c",
        "on-error-container": "#93000a",
        "surface-container-low": "#f4f3f3",
        "surface-dim": "#dadada",
        "surface": "#ffffff",
        "tertiary-fixed": "#ffdf92",
        "secondary": "#006590",
        "primary-container": "#58cc02",
        "error": "#ba1a1a",
        "on-secondary-container": "#004666",
        "surface-container-high": "#e9e8e8",
        "tertiary-container": "#ddad00",
        "on-error": "#ffffff",
        "on-background": "#1a1c1c",
        "on-surface-variant": "#3f4a36",
        "primary": "#2b6c00",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#755b00",
        "background": "#faf9f9"
      },
      spacing: {
        xs: "0.5rem",
        sm: "0.75rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "2.5rem",
        "3xl": "3rem",
      },
      fontSize: {
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "20px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "28px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["32px", { lineHeight: "40px" }],
        "4xl": ["40px", { lineHeight: "48px" }],
      },
      borderRadius: {
        none: "0",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        md: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
        xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
        "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s ease-out",
        "slide-down": "slideDown 0.3s ease-out",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "bounce-spring": "bounceSpring 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(0, 217, 125, 0.7)" },
          "50%": { boxShadow: "0 0 0 10px rgba(0, 217, 125, 0)" },
        },
        bounceSpring: {
          "0%": { transform: "scale(0.8)", opacity: "0" },
          "50%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      transitionDuration: {
        300: "300ms",
        400: "400ms",
        500: "500ms",
      },
    },
  },
  plugins: [],
};
