import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx,html}",
  ],
  theme: {
    extend: {
      colors: {
        // Base colors (from VISUAL_THESIS)
        "dark-bg": "#0F0F0F",
        "dark-surface": "#1A1A1A",
        "dark-surface-light": "#2A2A2A",
        "accent-green": "#00D97D",
        "accent-green-hover": "#00B85C",
        "text-primary": "#FFFFFF",
        "text-secondary": "#A0A0A0",
        "text-tertiary": "#707070",
        "error-red": "#EF4444",
        "success-green": "#10B981",
        "warning-orange": "#FFB563",
        "info-blue": "#06B6D4",
        
        // HTML Custom Screen Colors
        "secondary-fixed": "#c8e6ff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#88ceff",
        "on-surface-variant": "#3f4a36",
        "surface-bright": "#faf9f9",
        "primary": "#2b6c00",
        "outline-variant": "#becbb1",
        "primary-fixed": "#87fe45",
        "on-primary-fixed": "#082100",
        "surface-dim": "#dadada",
        "surface-container-low": "#f4f3f3",
        "on-tertiary-fixed": "#241a00",
        "secondary": "#006590",
        "on-error": "#ffffff",
        "outline": "#6f7b64",
        "on-background": "#1a1c1c",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c1c",
        "primary-container": "#58cc02",
        "surface-tint": "#2b6c00",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#f4bf00",
        "tertiary": "#755b00",
        "on-primary-fixed-variant": "#1f5100",
        "tertiary-container": "#ddad00",
        "on-tertiary-fixed-variant": "#594400",
        "on-secondary-container": "#004666",
        "secondary-container": "#2fb8ff",
        "on-secondary-fixed": "#001e2e",
        "on-tertiary-container": "#574300",
        "on-secondary-fixed-variant": "#004c6e",
        "tertiary-fixed": "#ffdf92",
        "surface-container-highest": "#e3e2e2",
        "surface-container": "#eeeeed",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f1f0f0",
        "surface-container-high": "#e9e8e8",
        "on-primary-container": "#1e5000",
        "surface-variant": "#e3e2e2",
        "background": "#faf9f9",
        "inverse-primary": "#6be026",
        "surface": "#faf9f9",
        "primary-fixed-dim": "#6be026",
        "inverse-surface": "#2f3131"
      },
      spacing: {
        // HTML Custom Spacing
        "max-width": "1200px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "base": "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        "2xl": "2.5rem",
        "3xl": "3rem",
      },
      fontFamily: {
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        // HTML Custom Fonts
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        // Base Overrides
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "20px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "28px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["32px", { lineHeight: "40px" }],
        "4xl": ["40px", { lineHeight: "48px" }],
      },
      borderRadius: {
        none: "0",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        md: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
        xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
        "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s ease-out",
        "slide-down": "slideDown 0.3s ease-out",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "bounce-spring": "bounceSpring 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(0, 217, 125, 0.7)" },
          "50%": { boxShadow: "0 0 0 10px rgba(0, 217, 125, 0)" },
        },
        bounceSpring: {
          "0%": { transform: "scale(0.8)", opacity: "0" },
          "50%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      transitionDuration: {
        300: "300ms",
        400: "400ms",
        500: "500ms",
      },
    },
  },
  plugins: [],
};

export default config;
